services:
  postgres:
    # UPDATED IMAGE: Changing to version 17 to match the existing data initialized by PostgreSQL version 17.
    image: postgres:17-alpine
    container_name: therapeia_postgres_db
    restart: unless-stopped

    # Environment variables are loaded from the .env file
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    # Map the configured host port to the internal PostgreSQL port (5432)
    ports:
      - "${POSTGRES_PORT}:5432"

    # Use a named volume to ensure data persists even if the container is stopped or removed
    volumes:
      - postgres_data:/var/lib/postgresql/data

# Define the named volume
volumes:
  postgres_data:
    driver: local
