[project]
name = "therapeia"
revision = "1.0"
# Extend configurations from subdirectories
# extends = [ "subdir1", "subdir2" ]

[profiles.default]
POSTGRES_DB = { description = "POSTGRES_DB secret", required = true }
POSTGRES_PASSWORD = { description = "POSTGRES_PASSWORD secret", required = true }
POSTGRES_USER = { description = "POSTGRES_USER secret", required = true }
POSTGRES_HOST = { description = "POSTGRES_HOST secret", required = true }
DATABASE_URL = { description = "DATABASE_URL secret", required = true }
POSTGRES_PORT = { description = "POSTGRES_PORT secret", required = true }
# DATABASE_URL = { description = "Database connection string", required = true }

[profiles.development]
# Development profile inherits all secrets from default profile
# Only define secrets here that need different values or settings than default
# DATABASE_URL = { default = "sqlite:///dev.db" }
#
# New secrets
# REDIS_URL = { description = "Redis connection URL for caching", required = false, default = "redis://localhost:6379" }
